"""Initial migration

Revision ID: 2d3fc9947c1b
Revises: 
Create Date: 2023-12-31 01:17:27.946988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3fc9947c1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('taskID', sa.String(length=50), nullable=False),
    sa.Column('sprint', sa.String(length=100), nullable=True),
    sa.Column('employeeName', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.String(length=20), nullable=False),
    sa.Column('endDate', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('taskID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
